@url = http://localhost:9999

###
GET {{url}}/api/messages

###
POST {{url}}/api/messages
Content-Type: application/json

{
    "id": "test",
    "content": "first message",
    "created": {{$timestamp}},
    "status": "MESSAGE_STATUS_PENDING"
}